version: "3.8"

# volumes:
#   minecraft:

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - VERSION=1.16.4
      - TYPE=PAPER
      - FORCE_REDOWNLOAD=true
    # volumes:
    #   - minecraft:/data
    configs:
      - source: server-properties
        target: /data/server.properties
    deploy:
      placement:
        constraints: [node.labels.elastic == true]

configs:
  server-properties:
    file: $PWD/data/server.properties
