version: "3.8"

# volumes:
#   plugins:

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - VERSION=1.16.4
      - TYPE=PAPER
      - FORCE_REDOWNLOAD=true
    volumes:
      - /home/ubuntu/plugins:/plugins
    configs:
      - source: server-properties
        target: /data/server.properties
      - source: plugins-vault-config
        target: /data/plugins/Vault/config.yml
    deploy:
      placement:
        constraints: [node.labels.elastic == true]

configs:
  server-properties:
    file: $PWD/data/server.properties
  plugins-vault-config:
    file: $PWD/data/plugins/Vault/config.yml
